-- ==============================
-- Ereft Hiking — Database Schema
-- Run this ONCE in Supabase SQL Editor
-- ==============================

-- EXTENSIONS
create extension if not exists pgcrypto;

-- SITE CONTENT (unchanged)
create table if not exists public.site_content (
  id text primary key default 'main',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- REGISTRATIONS (unchanged)
create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  hike_id text,
  user_id bigint references public.site_users(id) on delete set null,
  username text,
  full_name text not null,
  phone text not null,
  age int,
  participants_count int not null default 1,
  gender text,
  destination text not null,
  package_name text not null,
  trip_date text default '',
  price numeric(12,2) not null default 0,
  currency text not null default 'ETB',
  payment_method text default 'Not selected',
  sender_account text default '',
  transaction_id text default '',
  payment_status text not null default 'pending',
  status text not null default 'pending',
  lookup_token uuid not null default gen_random_uuid(),
  admin_message text default '',
  notes text default '',
  submitted_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- REGISTRATIONS CONSTRAINTS
alter table public.registrations drop constraint if exists registrations_status_check;
alter table public.registrations drop constraint if exists registrations_payment_status_check;
update public.registrations set payment_status = 'confirmed' where payment_status = 'paid';
update public.registrations set status = 'pending' where status not in ('pending', 'accepted', 'rejected', 'needs_review');
update public.registrations set payment_status = 'pending' where payment_status not in ('pending', 'submitted', 'confirmed', 'failed', 'refunded');
alter table public.registrations add constraint registrations_status_check check (status in ('pending', 'accepted', 'rejected', 'needs_review'));
alter table public.registrations add constraint registrations_payment_status_check check (payment_status in ('pending', 'submitted', 'confirmed', 'failed', 'refunded'));

-- ==============================
-- ADMINS (hardcoded login, no Supabase Auth)
-- ==============================
create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  display_name text not null default '',
  created_at timestamptz not null default now()
);

-- Insert default admin (username: admin, password: admin123)
insert into public.admins (username, password_hash, display_name)
values ('admin', crypt('admin123', gen_salt('bf')), 'Super Admin')
on conflict (username) do nothing;

-- ==============================
-- SITE USERS (main website login/signup)
-- ==============================
create table if not exists public.site_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  phone text default '',
  last_login timestamptz,
  created_at timestamptz not null default now()
);

-- ==============================
-- INDEXES
-- ==============================
create unique index if not exists registrations_hike_id_idx on public.registrations (hike_id);
create unique index if not exists registrations_lookup_token_idx on public.registrations (lookup_token);

-- ==============================
-- TRIGGERS: updated_at
-- ==============================
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_content_touch_updated_at on public.site_content;
create trigger site_content_touch_updated_at
before update on public.site_content
for each row execute function public.touch_updated_at();

drop trigger if exists registrations_touch_updated_at on public.registrations;
create trigger registrations_touch_updated_at
before update on public.registrations
for each row execute function public.touch_updated_at();

-- ==============================
-- RLS (disable for simplicity — admin bypasses anyway)
-- ==============================
alter table public.site_content disable row level security;
alter table public.registrations disable row level security;

-- ==============================
-- HELPER FUNCTIONS
-- ==============================
create or replace function public.generate_hike_id()
returns text
language plpgsql
as $$
declare
  candidate text;
begin
  loop
    candidate := 'HIK-' || upper(substr(translate(encode(gen_random_bytes(5), 'base64'), '+/=', ''), 1, 6));
    exit when not exists (select 1 from public.registrations where hike_id = candidate);
  end loop;
  return candidate;
end;
$$;

update public.registrations
set hike_id = public.generate_hike_id()
where hike_id is null or hike_id = '';

alter table public.registrations alter column hike_id set default public.generate_hike_id();
alter table public.registrations alter column hike_id set not null;

-- ==============================
-- ADMIN FUNCTIONS
-- ==============================

-- Admin login
create or replace function public.admin_login(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_record public.admins%rowtype;
begin
  select * into v_record from public.admins where username = p_username;
  if v_record.id is null then
    return jsonb_build_object('success', false, 'error', 'Invalid username or password');
  end if;
  if v_record.password_hash != crypt(p_password, v_record.password_hash) then
    return jsonb_build_object('success', false, 'error', 'Invalid username or password');
  end if;
  return jsonb_build_object('success', true, 'username', v_record.username, 'display_name', v_record.display_name);
end;
$$;
grant execute on function public.admin_login(text, text) to anon, authenticated;

-- Add admin
create or replace function public.add_admin(p_username text, p_password text, p_display_name text default '')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.admins (username, password_hash, display_name)
  values (p_username, crypt(p_password, gen_salt('bf')), p_display_name);
  return jsonb_build_object('success', true);
exception when unique_violation then
  return jsonb_build_object('success', false, 'error', 'Username already exists');
end;
$$;
grant execute on function public.add_admin(text, text, text) to anon, authenticated;

-- Get all site users (for admin panel)
create or replace function public.get_site_users()
returns table (username text, phone text, last_login timestamptz, created_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select username, phone, last_login, created_at from public.site_users order by created_at desc;
$$;
grant execute on function public.get_site_users() to anon, authenticated;

-- Delete site user
create or replace function public.delete_site_user(p_username text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.site_users where username = p_username;
  return found;
end;
$$;
grant execute on function public.delete_site_user(text) to anon, authenticated;

-- ==============================
-- USER FUNCTIONS (main website)
-- ==============================

-- Signup
create or replace function public.user_signup(p_username text, p_password text, p_phone text default '')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (select 1 from public.site_users where username = p_username) then
    return jsonb_build_object('success', false, 'error', 'Username already exists');
  end if;
  insert into public.site_users (username, password_hash, phone)
  values (p_username, crypt(p_password, gen_salt('bf')), p_phone);
  return jsonb_build_object('success', true);
end;
$$;
grant execute on function public.user_signup(text, text, text) to anon, authenticated;

-- Login
create or replace function public.user_login(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_record public.site_users%rowtype;
begin
  select * into v_record from public.site_users where username = p_username;
  if v_record.id is null then
    return jsonb_build_object('success', false, 'error', 'Invalid username or password');
  end if;
  if v_record.password_hash != crypt(p_password, v_record.password_hash) then
    return jsonb_build_object('success', false, 'error', 'Invalid username or password');
  end if;
  update public.site_users set last_login = now() where id = v_record.id;
  return jsonb_build_object('success', true, 'username', v_record.username, 'phone', v_record.phone);
end;
$$;
grant execute on function public.user_login(text, text) to anon, authenticated;

-- ==============================
-- BOOKING FUNCTION
-- ==============================
create or replace function public.create_booking(
  p_full_name text,
  p_phone text,
  p_age int,
  p_participants_count int,
  p_gender text,
  p_destination text,
  p_package_name text,
  p_trip_date text,
  p_price numeric,
  p_currency text,
  p_payment_method text,
  p_sender_account text,
  p_transaction_id text
)
returns table (
  id bigint,
  hike_id text,
  user_id bigint,
  username text,
  full_name text,
  phone text,
  participants_count int,
  destination text,
  package_name text,
  trip_date text,
  price numeric,
  currency text,
  payment_method text,
  sender_account text,
  transaction_id text,
  status text,
  payment_status text,
  admin_message text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id bigint;
  v_username text;
  v_payment_status text;
  v_payload jsonb;
  v_package jsonb;
  v_price numeric;
  v_currency text;
begin
  -- Get current user from site_users
  select su.id, su.username into v_user_id, v_username
  from public.site_users su
  where su.username = current_setting('app.current_user', true);

  if v_user_id is null then
    raise exception 'Login is required to create a booking.';
  end if;

  v_payment_status := case
    when coalesce(nullif(p_sender_account, ''), nullif(p_transaction_id, '')) is not null then 'submitted'
    else 'pending'
  end;

  select site_content.payload into v_payload
  from public.site_content where site_content.id = 'main';

  select package_item into v_package
  from jsonb_array_elements(jsonb_build_array(
    v_payload #> '{packages,nativeDay}',
    v_payload #> '{packages,nativeOvernight}',
    v_payload #> '{packages,foreignerDay}',
    v_payload #> '{packages,foreignerOvernight}'
  )) as packages(package_item)
  where package_item is not null and package_item ->> 'name' = p_package_name
  limit 1;

  v_price := coalesce(nullif(v_package ->> 'price', '')::numeric, p_price, 0);
  v_currency := coalesce(nullif(v_package ->> 'currency', ''), nullif(p_currency, ''), 'ETB');

  return query
  insert into public.registrations (
    user_id, username, full_name, phone, age, participants_count,
    gender, destination, package_name, trip_date, price, currency,
    payment_method, sender_account, transaction_id, payment_status, status
  ) values (
    v_user_id, v_username, trim(p_full_name), trim(p_phone),
    p_age, greatest(1, coalesce(p_participants_count, 1)),
    p_gender, p_destination, p_package_name, coalesce(p_trip_date, ''),
    v_price, v_currency,
    coalesce(nullif(p_payment_method, ''), 'Not selected'),
    coalesce(p_sender_account, ''), coalesce(p_transaction_id, ''),
    v_payment_status, 'pending'
  )
  returning
    registrations.id, registrations.hike_id, registrations.user_id,
    registrations.username, registrations.full_name, registrations.phone,
    registrations.participants_count, registrations.destination,
    registrations.package_name, registrations.trip_date,
    registrations.price, registrations.currency,
    registrations.payment_method, registrations.sender_account,
    registrations.transaction_id, registrations.status,
    registrations.payment_status, registrations.admin_message,
    registrations.created_at, registrations.updated_at;
end;
$$;

grant execute on function public.create_booking(text, text, int, int, text, text, text, text, numeric, text, text, text, text) to anon, authenticated;

-- ==============================
-- DEFAULT CONTENT
-- ==============================
insert into public.site_content (id, payload)
values ('main', '{}'::jsonb)
on conflict (id) do nothing;
