create extension if not exists pgcrypto;

create table if not exists public.site_content (
  id text primary key default 'main',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[a-z0-9._-]{3,30}$'),
  phone text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  hike_id text,
  user_id uuid references auth.users(id) on delete set null,
  username text,
  full_name text not null,
  phone text not null,
  age int,
  participants_count int not null default 1,
  gender text,
  destination text not null,
  package_name text not null,
  trip_date text default '',
  price numeric(12,2) not null default 0,
  currency text not null default 'ETB',
  payment_method text default 'Not selected',
  sender_account text default '',
  transaction_id text default '',
  payment_status text not null default 'pending',
  status text not null default 'pending',
  lookup_token uuid not null default gen_random_uuid(),
  admin_message text default '',
  notes text default '',
  submitted_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.registrations add column if not exists hike_id text;
alter table public.registrations add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.registrations add column if not exists username text;
alter table public.registrations add column if not exists participants_count int not null default 1;
alter table public.registrations add column if not exists trip_date text default '';
alter table public.registrations add column if not exists price numeric(12,2) not null default 0;
alter table public.registrations add column if not exists currency text not null default 'ETB';
alter table public.registrations add column if not exists sender_account text default '';
alter table public.registrations add column if not exists transaction_id text default '';
alter table public.registrations add column if not exists admin_message text default '';
alter table public.registrations add column if not exists lookup_token uuid not null default gen_random_uuid();

alter table public.registrations drop constraint if exists registrations_status_check;
alter table public.registrations drop constraint if exists registrations_payment_status_check;

update public.registrations set payment_status = 'confirmed' where payment_status = 'paid';
update public.registrations set status = 'pending' where status not in ('pending', 'accepted', 'rejected', 'needs_review');
update public.registrations set payment_status = 'pending' where payment_status not in ('pending', 'submitted', 'confirmed', 'failed', 'refunded');

alter table public.registrations
  add constraint registrations_status_check
  check (status in ('pending', 'accepted', 'rejected', 'needs_review'));

alter table public.registrations
  add constraint registrations_payment_status_check
  check (payment_status in ('pending', 'submitted', 'confirmed', 'failed', 'refunded'));

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.normalize_username(p_username text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(trim(coalesce(p_username, '')), '[^a-z0-9._-]', '', 'g'));
$$;

create or replace function public.generate_hike_id()
returns text
language plpgsql
as $$
declare
  candidate text;
begin
  loop
    candidate := 'HIK-' || upper(substr(translate(encode(gen_random_bytes(5), 'base64'), '+/=', ''), 1, 6));
    exit when not exists (select 1 from public.registrations where hike_id = candidate);
  end loop;
  return candidate;
end;
$$;

update public.registrations
set hike_id = public.generate_hike_id()
where hike_id is null or hike_id = '';

alter table public.registrations alter column hike_id set default public.generate_hike_id();
alter table public.registrations alter column hike_id set not null;

create unique index if not exists registrations_hike_id_idx on public.registrations (hike_id);
create unique index if not exists registrations_lookup_token_idx on public.registrations (lookup_token);
create unique index if not exists profiles_username_idx on public.profiles (username);

drop trigger if exists site_content_touch_updated_at on public.site_content;
create trigger site_content_touch_updated_at
before update on public.site_content
for each row execute function public.touch_updated_at();

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists registrations_touch_updated_at on public.registrations;
create trigger registrations_touch_updated_at
before update on public.registrations
for each row execute function public.touch_updated_at();

alter table public.site_content enable row level security;
alter table public.admin_users enable row level security;
alter table public.profiles enable row level security;
alter table public.registrations enable row level security;

drop policy if exists "Admins can read admin users" on public.admin_users;
create policy "Admins can read admin users"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can create own profile" on public.profiles;
create policy "Users can create own profile"
on public.profiles for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Admins can read profiles" on public.profiles;
create policy "Admins can read profiles"
on public.profiles for select
to authenticated
using (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Anyone can read published site content" on public.site_content;
create policy "Anyone can read published site content"
on public.site_content for select
to anon, authenticated
using (id = 'main');

drop policy if exists "Admins can manage site content" on public.site_content;
create policy "Admins can manage site content"
on public.site_content for all
to authenticated
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Visitors can create registrations" on public.registrations;
drop policy if exists "Users can create own registrations" on public.registrations;
drop policy if exists "Users can read own registrations" on public.registrations;
drop policy if exists "Admins can read registrations" on public.registrations;
drop policy if exists "Admins can update registrations" on public.registrations;

create policy "Users can read own registrations"
on public.registrations for select
to authenticated
using (user_id = auth.uid());

create policy "Admins can read registrations"
on public.registrations for select
to authenticated
using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can update registrations"
on public.registrations for update
to authenticated
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create or replace function public.is_username_available(p_username text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not exists (
    select 1 from public.profiles
    where username = public.normalize_username(p_username)
  );
$$;

create or replace function public.create_booking(
  p_full_name text,
  p_phone text,
  p_age int,
  p_participants_count int,
  p_gender text,
  p_destination text,
  p_package_name text,
  p_trip_date text,
  p_price numeric,
  p_currency text,
  p_payment_method text,
  p_sender_account text,
  p_transaction_id text
)
returns table (
  id bigint,
  hike_id text,
  user_id uuid,
  username text,
  full_name text,
  phone text,
  participants_count int,
  destination text,
  package_name text,
  trip_date text,
  price numeric,
  currency text,
  payment_method text,
  sender_account text,
  transaction_id text,
  status text,
  payment_status text,
  admin_message text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_username text;
  v_payment_status text;
  v_payload jsonb;
  v_package jsonb;
  v_price numeric;
  v_currency text;
begin
  if v_user is null then
    raise exception 'Login is required to create a booking.';
  end if;

  select profiles.username into v_username
  from public.profiles
  where profiles.user_id = v_user;

  if v_username is null then
    v_username := public.normalize_username(coalesce(auth.jwt() -> 'user_metadata' ->> 'username', split_part(auth.jwt() ->> 'email', '@', 1)));
    insert into public.profiles (user_id, username, phone)
    values (v_user, v_username, coalesce(nullif(p_phone, ''), ''))
    on conflict (user_id) do nothing;
  end if;

  v_payment_status := case
    when coalesce(nullif(p_sender_account, ''), nullif(p_transaction_id, '')) is not null then 'submitted'
    else 'pending'
  end;

  select site_content.payload into v_payload
  from public.site_content
  where site_content.id = 'main';

  select package_item into v_package
  from jsonb_array_elements(jsonb_build_array(
    v_payload #> '{packages,nativeDay}',
    v_payload #> '{packages,nativeOvernight}',
    v_payload #> '{packages,foreignerDay}',
    v_payload #> '{packages,foreignerOvernight}'
  )) as packages(package_item)
  where package_item is not null
    and package_item ->> 'name' = p_package_name
  limit 1;

  v_price := coalesce(nullif(v_package ->> 'price', '')::numeric, p_price, 0);
  v_currency := coalesce(nullif(v_package ->> 'currency', ''), nullif(p_currency, ''), 'ETB');

  return query
  insert into public.registrations (
    user_id,
    username,
    full_name,
    phone,
    age,
    participants_count,
    gender,
    destination,
    package_name,
    trip_date,
    price,
    currency,
    payment_method,
    sender_account,
    transaction_id,
    payment_status,
    status
  )
  values (
    v_user,
    v_username,
    trim(p_full_name),
    trim(p_phone),
    p_age,
    greatest(1, coalesce(p_participants_count, 1)),
    p_gender,
    p_destination,
    p_package_name,
    coalesce(p_trip_date, ''),
    v_price,
    v_currency,
    coalesce(nullif(p_payment_method, ''), 'Not selected'),
    coalesce(p_sender_account, ''),
    coalesce(p_transaction_id, ''),
    v_payment_status,
    'pending'
  )
  returning
    registrations.id,
    registrations.hike_id,
    registrations.user_id,
    registrations.username,
    registrations.full_name,
    registrations.phone,
    registrations.participants_count,
    registrations.destination,
    registrations.package_name,
    registrations.trip_date,
    registrations.price,
    registrations.currency,
    registrations.payment_method,
    registrations.sender_account,
    registrations.transaction_id,
    registrations.status,
    registrations.payment_status,
    registrations.admin_message,
    registrations.created_at,
    registrations.updated_at;
end;
$$;

create or replace function public.submit_booking_payment(
  p_hike_id text,
  p_sender_account text,
  p_transaction_id text
)
returns table (
  id bigint,
  hike_id text,
  status text,
  payment_status text,
  sender_account text,
  transaction_id text,
  admin_message text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'Login is required to submit payment details.';
  end if;

  return query
  update public.registrations r
  set
    sender_account = coalesce(p_sender_account, ''),
    transaction_id = coalesce(p_transaction_id, ''),
    payment_status = 'submitted',
    status = case when r.status in ('accepted', 'rejected') then r.status else 'pending' end
  where r.hike_id = p_hike_id
    and r.user_id = v_user
  returning
    r.id,
    r.hike_id,
    r.status,
    r.payment_status,
    r.sender_account,
    r.transaction_id,
    r.admin_message,
    r.updated_at;
end;
$$;

create or replace function public.get_registration_status(p_lookup_token uuid)
returns table (
  id bigint,
  lookup_token uuid,
  hike_id text,
  status text,
  payment_status text,
  destination text,
  package_name text,
  submitted_date date,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    r.id,
    r.lookup_token,
    r.hike_id,
    r.status,
    r.payment_status,
    r.destination,
    r.package_name,
    r.submitted_date,
    r.updated_at
  from public.registrations r
  where r.lookup_token = p_lookup_token
  limit 1;
$$;

grant execute on function public.is_username_available(text) to anon, authenticated;
grant execute on function public.create_booking(text, text, int, int, text, text, text, text, numeric, text, text, text, text) to authenticated;
grant execute on function public.submit_booking_payment(text, text, text) to authenticated;
grant execute on function public.get_registration_status(uuid) to anon, authenticated;

insert into public.site_content (id, payload)
values ('main', '{}'::jsonb)
on conflict (id) do nothing;

-- Add last_login column to profiles for tracking user activity
alter table public.profiles add column if not exists last_login timestamptz;

-- Function: create a user with confirmed email (bypass email verification)
create or replace function public.create_user_with_confirmed_email(
  p_username text,
  p_password text,
  p_phone text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_email text;
  v_username text;
begin
  v_username := public.normalize_username(p_username);
  v_email := v_username || '@ereft.local';

  -- Create user in auth.users with email auto-confirmed
  insert into auth.users (
    email,
    encrypted_password,
    email_confirmed_at,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    email_change,
    email_change_token_new,
    email_change_token_current
  ) values (
    v_email,
    crypt(p_password, gen_salt('bf')),
    now(),
    jsonb_build_object('username', v_username, 'phone', p_phone),
    now(),
    now(),
    '',
    now(),
    '',
    '',
    '',
    ''
  ) returning id into v_user_id;

  -- Create profile
  insert into public.profiles (user_id, username, phone)
  values (v_user_id, v_username, p_phone)
  on conflict (user_id) do nothing;

  return jsonb_build_object('success', true, 'user_id', v_user_id::text);
exception
  when unique_violation then
    return jsonb_build_object('success', false, 'error', 'Username or email already exists');
  when others then
    return jsonb_build_object('success', false, 'error', SQLERRM);
end;
$$;

grant execute on function public.create_user_with_confirmed_email(text, text, text) to anon, authenticated;

-- ==============================
-- ADMIN CREDENTIALS (hardcoded login, no Supabase Auth needed)
-- ==============================
create table if not exists public.admin_credentials (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  display_name text not null default '',
  supabase_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Insert default admin (username: admin, password: admin123)
insert into public.admin_credentials (username, password_hash, display_name)
values ('admin', crypt('admin123', gen_salt('bf')), 'Super Admin')
on conflict (username) do nothing;

-- Function: create/get linked Supabase Auth user for an admin
create or replace function public.setup_admin_auth_user(p_admin_username text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_email text;
  v_password text := 'ereft_admin_supabase_2024';
begin
  v_email := p_admin_username || '@admin.ereft.local';

  select id into v_user_id from auth.users where email = v_email;

  if v_user_id is null then
    insert into auth.users (
      id, email, encrypted_password, email_confirmed_at,
      raw_user_meta_data, created_at, updated_at,
      confirmation_token, confirmation_sent_at,
      recovery_token, email_change,
      email_change_token_new, email_change_token_current,
      instance_id, aud, role,
      is_super_admin, is_sso_user
    ) values (
      gen_random_uuid(), v_email, crypt(v_password, gen_salt('bf')), now(),
      jsonb_build_object('username', p_admin_username), now(), now(),
      '', now(), '', '', '', '',
      '00000000-0000-0000-0000-000000000000'::uuid, 'authenticated', 'authenticated',
      false, false
    )
    returning id into v_user_id;

    insert into public.admin_users (user_id, email)
    values (v_user_id, v_email)
    on conflict (user_id) do nothing;

    insert into public.profiles (user_id, username, phone)
    values (v_user_id, p_admin_username, '')
    on conflict (user_id) do nothing;
  end if;

  update public.admin_credentials
  set supabase_user_id = v_user_id
  where username = p_admin_username;

  return jsonb_build_object('success', true, 'user_id', v_user_id::text, 'email', v_email);
end;
$$;

grant execute on function public.setup_admin_auth_user(text) to anon, authenticated;

-- Function: admin login (checks admin_credentials, NOT Supabase Auth)
create or replace function public.admin_login(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_record public.admin_credentials%rowtype;
begin
  select * into v_record from public.admin_credentials where username = p_username;

  if v_record.id is null then
    return jsonb_build_object('success', false, 'error', 'Invalid username or password');
  end if;

  if v_record.password_hash != crypt(p_password, v_record.password_hash) then
    return jsonb_build_object('success', false, 'error', 'Invalid username or password');
  end if;

  return jsonb_build_object(
    'success', true,
    'username', v_record.username,
    'display_name', v_record.display_name
  );
end;
$$;

grant execute on function public.admin_login(text, text) to anon, authenticated;

-- Function: add new admin credentials
create or replace function public.add_admin_credentials(p_username text, p_password text, p_display_name text default '')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.admin_credentials (username, password_hash, display_name)
  values (p_username, crypt(p_password, gen_salt('bf')), p_display_name);
  return jsonb_build_object('success', true);
exception when unique_violation then
  return jsonb_build_object('success', false, 'error', 'Username already exists');
end;
$$;

grant execute on function public.add_admin_credentials(text, text, text) to authenticated;

-- Admin function: delete a user by their user_id (cascades to profiles, admin_users, etc.)
create or replace function public.delete_user(p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from public.admin_users where user_id = auth.uid()) then
    raise exception 'Only admins can delete users';
  end if;
  if p_user_id = auth.uid() then
    raise exception 'You cannot delete your own account';
  end if;
  if exists (select 1 from public.admin_users where user_id = p_user_id) then
    raise exception 'Cannot delete an admin user. Remove from admin_users first.';
  end if;
  delete from auth.users where id = p_user_id;
  return found;
end;
$$;

grant execute on function public.delete_user(uuid) to authenticated;

-- Backfill: create profiles for existing auth users who signed up before the trigger existed
insert into public.profiles (user_id, username, phone)
select
  au.id,
  public.normalize_username(coalesce(au.raw_user_meta_data ->> 'username', split_part(au.email, '@', 1))),
  coalesce(au.raw_user_meta_data ->> 'phone', '')
from auth.users au
left join public.profiles p on p.user_id = au.id
where p.user_id is null
on conflict (user_id) do nothing;

-- Auto-create profile when a new user signs up (trigger on auth.users)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, username, phone)
  values (
    new.id,
    public.normalize_username(coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1))),
    coalesce(new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
