-- Ereft Hiking clean Supabase setup
-- Run this whole file in Supabase SQL Editor when starting fresh.
-- Public website users and admin users are separate database logins.
-- Supabase Authentication is not used by this setup.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
set search_path = public, extensions;

-- Remove old mixed-auth objects if they exist.
drop function if exists public.create_booking(text, text, int, int, text, text, text, text, numeric, text, text, text, text);
drop function if exists public.submit_booking_payment(text, text, text);
drop function if exists public.is_username_available(text);
drop function if exists public.setup_admin_auth_user(text);
drop function if exists public.add_admin_credentials(text, text, text);
drop function if exists public.delete_user(uuid);
drop function if exists public.delete_site_user(text);
drop function if exists public.get_site_users();
drop table if exists public.admin_sessions cascade;
drop table if exists public.site_user_sessions cascade;
drop table if exists public.registrations cascade;
drop table if exists public.site_users cascade;
drop table if exists public.admins cascade;
drop table if exists public.admin_users cascade;
drop table if exists public.profiles cascade;

-- Main content edited by admin and read by public website.
create table if not exists public.site_content (
  id text primary key default 'main',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_defaults (
  id text primary key default 'main',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- Admin accounts are only for admin/index.html.
create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  display_name text not null default '',
  last_login timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_sessions (
  token uuid primary key default extensions.gen_random_uuid(),
  admin_id bigint not null references public.admins(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '30 days'
);

-- Public website accounts are only for index.html signup/login.
create table if not exists public.site_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  phone text default '',
  last_login timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_user_sessions (
  token uuid primary key default extensions.gen_random_uuid(),
  user_id bigint not null references public.site_users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '60 days'
);

-- Bookings/registrations created by logged-in public users.
create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  hike_id text,
  user_id bigint references public.site_users(id) on delete set null,
  username text,
  full_name text not null,
  phone text not null,
  age int,
  participants_count int not null default 1,
  gender text,
  destination text not null,
  package_name text not null,
  trip_date text default '',
  price numeric(12,2) not null default 0,
  currency text not null default 'ETB',
  payment_method text default 'Not selected',
  sender_account text default '',
  transaction_id text default '',
  payment_status text not null default 'pending',
  status text not null default 'pending',
  lookup_token uuid not null default extensions.gen_random_uuid(),
  admin_message text default '',
  notes text default '',
  submitted_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.registrations drop constraint if exists registrations_status_check;
alter table public.registrations drop constraint if exists registrations_payment_status_check;
update public.registrations set payment_status = 'confirmed' where payment_status = 'paid';
update public.registrations set status = 'pending' where status not in ('pending', 'accepted', 'rejected', 'needs_review');
update public.registrations set payment_status = 'pending' where payment_status not in ('pending', 'submitted', 'confirmed', 'failed', 'refunded');
alter table public.registrations add constraint registrations_status_check check (status in ('pending', 'accepted', 'rejected', 'needs_review'));
alter table public.registrations add constraint registrations_payment_status_check check (payment_status in ('pending', 'submitted', 'confirmed', 'failed', 'refunded'));

create unique index if not exists registrations_hike_id_idx on public.registrations (hike_id);
create unique index if not exists registrations_lookup_token_idx on public.registrations (lookup_token);
create index if not exists registrations_user_id_idx on public.registrations (user_id);
create index if not exists registrations_created_at_idx on public.registrations (created_at desc);
create index if not exists site_users_created_at_idx on public.site_users (created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_content_touch_updated_at on public.site_content;
create trigger site_content_touch_updated_at
before update on public.site_content
for each row execute function public.touch_updated_at();

drop trigger if exists site_defaults_touch_updated_at on public.site_defaults;
create trigger site_defaults_touch_updated_at
before update on public.site_defaults
for each row execute function public.touch_updated_at();

drop trigger if exists admins_touch_updated_at on public.admins;
create trigger admins_touch_updated_at
before update on public.admins
for each row execute function public.touch_updated_at();

drop trigger if exists site_users_touch_updated_at on public.site_users;
create trigger site_users_touch_updated_at
before update on public.site_users
for each row execute function public.touch_updated_at();

drop trigger if exists registrations_touch_updated_at on public.registrations;
create trigger registrations_touch_updated_at
before update on public.registrations
for each row execute function public.touch_updated_at();

create or replace function public.normalize_login_name(value text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(trim(coalesce(value, '')), '[^a-zA-Z0-9._-]', '', 'g'));
$$;

create or replace function public.generate_hike_id()
returns text
language plpgsql
as $$
declare
  candidate text;
begin
  loop
    candidate := 'HIK-' || upper(substr(translate(encode(gen_random_bytes(5), 'base64'), '+/=', ''), 1, 6));
    exit when not exists (select 1 from public.registrations where hike_id = candidate);
  end loop;
  return candidate;
end;
$$;

update public.registrations
set hike_id = public.generate_hike_id()
where hike_id is null or hike_id = '';

alter table public.registrations alter column hike_id set default public.generate_hike_id();
alter table public.registrations alter column hike_id set not null;

create or replace function public.valid_admin(p_admin_token uuid)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_admin_id bigint;
begin
  select admin_id into v_admin_id
  from public.admin_sessions
  where token = p_admin_token
    and expires_at > now();

  if v_admin_id is null then
    raise exception 'Admin login required.';
  end if;

  return v_admin_id;
end;
$$;

create or replace function public.valid_site_user(p_session_token uuid)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id bigint;
begin
  select user_id into v_user_id
  from public.site_user_sessions
  where token = p_session_token
    and expires_at > now();

  if v_user_id is null then
    raise exception 'Login is required.';
  end if;

  return v_user_id;
end;
$$;

-- Default admin. Change this password inside the admin settings after setup.
insert into public.admins (username, password_hash, display_name)
values ('admin', extensions.crypt('admin123', extensions.gen_salt('bf')), 'Default Admin')
on conflict (username) do update
set password_hash = excluded.password_hash,
    display_name = excluded.display_name,
    updated_at = now();

-- Public content can be read by the public website.
insert into public.site_content (id, payload)
values ('main', '{}'::jsonb)
on conflict (id) do nothing;

insert into public.site_defaults (id, payload)
values ('main', '{}'::jsonb)
on conflict (id) do nothing;

-- Admin login.
create or replace function public.admin_login(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_admin public.admins%rowtype;
  v_token uuid;
begin
  select * into v_admin
  from public.admins
  where username = public.normalize_login_name(p_username);

  if v_admin.id is null or v_admin.password_hash <> extensions.crypt(coalesce(p_password, ''), v_admin.password_hash) then
    return jsonb_build_object('success', false, 'error', 'Invalid username or password');
  end if;

  insert into public.admin_sessions (admin_id) values (v_admin.id)
  returning token into v_token;

  update public.admins set last_login = now() where id = v_admin.id;

  return jsonb_build_object(
    'success', true,
    'session_token', v_token,
    'admin', jsonb_build_object(
      'id', v_admin.id,
      'username', v_admin.username,
      'display_name', coalesce(nullif(v_admin.display_name, ''), v_admin.username)
    )
  );
end;
$$;

create or replace function public.admin_current(p_admin_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_admin public.admins%rowtype;
begin
  select a.* into v_admin
  from public.admins a
  where a.id = public.valid_admin(p_admin_token);

  return jsonb_build_object(
    'success', true,
    'admin', jsonb_build_object(
      'id', v_admin.id,
      'username', v_admin.username,
      'display_name', coalesce(nullif(v_admin.display_name, ''), v_admin.username)
    )
  );
end;
$$;

create or replace function public.admin_logout(p_admin_token uuid)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  delete from public.admin_sessions where token = p_admin_token;
  return true;
end;
$$;

create or replace function public.admin_add_admin(
  p_admin_token uuid,
  p_username text,
  p_password text,
  p_display_name text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_username text := public.normalize_login_name(p_username);
begin
  perform public.valid_admin(p_admin_token);

  if length(v_username) < 3 then
    return jsonb_build_object('success', false, 'error', 'Username must be at least 3 characters.');
  end if;
  if length(coalesce(p_password, '')) < 6 then
    return jsonb_build_object('success', false, 'error', 'Password must be at least 6 characters.');
  end if;

  insert into public.admins (username, password_hash, display_name)
  values (v_username, extensions.crypt(p_password, extensions.gen_salt('bf')), coalesce(nullif(trim(p_display_name), ''), v_username));

  return jsonb_build_object('success', true);
exception when unique_violation then
  return jsonb_build_object('success', false, 'error', 'Admin username already exists.');
end;
$$;

create or replace function public.admin_update_profile(p_admin_token uuid, p_display_name text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_admin_id bigint;
  v_admin public.admins%rowtype;
begin
  v_admin_id := public.valid_admin(p_admin_token);
  update public.admins
  set display_name = coalesce(nullif(trim(p_display_name), ''), username)
  where id = v_admin_id
  returning * into v_admin;

  return jsonb_build_object(
    'success', true,
    'admin', jsonb_build_object(
      'id', v_admin.id,
      'username', v_admin.username,
      'display_name', coalesce(nullif(v_admin.display_name, ''), v_admin.username)
    )
  );
end;
$$;

create or replace function public.admin_change_password(
  p_admin_token uuid,
  p_current_password text,
  p_new_password text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_admin_id bigint;
  v_admin public.admins%rowtype;
begin
  v_admin_id := public.valid_admin(p_admin_token);
  select * into v_admin from public.admins where id = v_admin_id;

  if v_admin.password_hash <> extensions.crypt(coalesce(p_current_password, ''), v_admin.password_hash) then
    return jsonb_build_object('success', false, 'error', 'Current password is incorrect.');
  end if;
  if length(coalesce(p_new_password, '')) < 6 then
    return jsonb_build_object('success', false, 'error', 'New password must be at least 6 characters.');
  end if;

  update public.admins
  set password_hash = extensions.crypt(p_new_password, extensions.gen_salt('bf'))
  where id = v_admin_id;

  return jsonb_build_object('success', true);
end;
$$;

create or replace function public.admin_get_content(p_admin_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_payload jsonb;
begin
  perform public.valid_admin(p_admin_token);
  select payload into v_payload from public.site_content where id = 'main';
  return coalesce(v_payload, '{}'::jsonb);
end;
$$;

create or replace function public.admin_save_content(p_admin_token uuid, p_payload jsonb)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  perform public.valid_admin(p_admin_token);
  insert into public.site_content (id, payload)
  values ('main', coalesce(p_payload, '{}'::jsonb))
  on conflict (id) do update set payload = excluded.payload;
  return true;
end;
$$;

create or replace function public.admin_get_registrations(p_admin_token uuid)
returns setof public.registrations
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  perform public.valid_admin(p_admin_token);
  return query select * from public.registrations order by created_at desc;
end;
$$;

create or replace function public.admin_get_site_users(p_admin_token uuid)
returns table (
  id bigint,
  username text,
  phone text,
  last_login timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  perform public.valid_admin(p_admin_token);
  return query
    select u.id, u.username, u.phone, u.last_login, u.created_at
    from public.site_users u
    order by u.created_at desc;
end;
$$;

create or replace function public.admin_delete_site_user(p_admin_token uuid, p_user_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  perform public.valid_admin(p_admin_token);
  delete from public.site_users where id = p_user_id;
  return found;
end;
$$;

create or replace function public.admin_update_registration(
  p_admin_token uuid,
  p_registration_id bigint,
  p_status text default null,
  p_admin_message text default null
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_payment_status text;
begin
  perform public.valid_admin(p_admin_token);

  if p_status is not null and p_status not in ('pending', 'accepted', 'rejected', 'needs_review') then
    raise exception 'Invalid registration status.';
  end if;

  v_payment_status := case
    when p_status = 'accepted' then 'confirmed'
    when p_status = 'rejected' then 'failed'
    when p_status = 'needs_review' then 'submitted'
    when p_status = 'pending' then 'pending'
    else null
  end;

  update public.registrations
  set
    status = coalesce(p_status, status),
    payment_status = coalesce(v_payment_status, payment_status),
    admin_message = case when p_admin_message is null then admin_message else p_admin_message end
  where id = p_registration_id;

  return found;
end;
$$;

-- Public site auth.
create or replace function public.user_signup(
  p_username text,
  p_password text,
  p_phone text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_username text := public.normalize_login_name(p_username);
  v_user public.site_users%rowtype;
  v_token uuid;
begin
  if length(v_username) < 3 then
    return jsonb_build_object('success', false, 'error', 'Username must be at least 3 characters.');
  end if;
  if length(coalesce(p_password, '')) < 6 then
    return jsonb_build_object('success', false, 'error', 'Password must be at least 6 characters.');
  end if;

  insert into public.site_users (username, password_hash, phone, last_login)
  values (v_username, extensions.crypt(p_password, extensions.gen_salt('bf')), coalesce(trim(p_phone), ''), now())
  returning * into v_user;

  insert into public.site_user_sessions (user_id) values (v_user.id)
  returning token into v_token;

  return jsonb_build_object(
    'success', true,
    'session_token', v_token,
    'user', jsonb_build_object(
      'id', v_user.id,
      'username', v_user.username,
      'phone', v_user.phone
    )
  );
exception when unique_violation then
  return jsonb_build_object('success', false, 'error', 'Username already exists.');
end;
$$;

create or replace function public.user_login(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.site_users%rowtype;
  v_token uuid;
begin
  select * into v_user
  from public.site_users
  where username = public.normalize_login_name(p_username);

  if v_user.id is null or v_user.password_hash <> extensions.crypt(coalesce(p_password, ''), v_user.password_hash) then
    return jsonb_build_object('success', false, 'error', 'Invalid username or password');
  end if;

  insert into public.site_user_sessions (user_id) values (v_user.id)
  returning token into v_token;

  update public.site_users set last_login = now() where id = v_user.id;

  return jsonb_build_object(
    'success', true,
    'session_token', v_token,
    'user', jsonb_build_object(
      'id', v_user.id,
      'username', v_user.username,
      'phone', v_user.phone
    )
  );
end;
$$;

create or replace function public.get_current_user(p_session_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.site_users%rowtype;
begin
  select * into v_user
  from public.site_users
  where id = public.valid_site_user(p_session_token);

  return jsonb_build_object(
    'success', true,
    'user', jsonb_build_object(
      'id', v_user.id,
      'username', v_user.username,
      'phone', v_user.phone
    )
  );
end;
$$;

create or replace function public.user_logout(p_session_token uuid)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  delete from public.site_user_sessions where token = p_session_token;
  return true;
end;
$$;

create or replace function public.create_booking(
  p_session_token uuid,
  p_full_name text,
  p_phone text,
  p_age int,
  p_participants_count int,
  p_gender text,
  p_destination text,
  p_package_name text,
  p_trip_date text,
  p_price numeric,
  p_currency text,
  p_payment_method text,
  p_sender_account text,
  p_transaction_id text
)
returns setof public.registrations
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.site_users%rowtype;
  v_payment_status text;
  v_payload jsonb;
  v_package jsonb;
  v_price numeric;
  v_currency text;
begin
  select * into v_user
  from public.site_users
  where id = public.valid_site_user(p_session_token);

  if trim(coalesce(p_full_name, '')) = '' then
    raise exception 'Full name is required.';
  end if;
  if trim(coalesce(p_phone, '')) = '' then
    raise exception 'Phone number is required.';
  end if;
  if trim(coalesce(p_destination, '')) = '' or trim(coalesce(p_package_name, '')) = '' then
    raise exception 'Destination and package are required.';
  end if;

  v_payment_status := case
    when nullif(trim(p_sender_account), '') is not null then 'submitted'
    else 'pending'
  end;

  select sc.payload into v_payload
  from public.site_content sc where sc.id = 'main';

  if v_payload is not null then
    select package_item into v_package
    from jsonb_array_elements(jsonb_build_array(
      v_payload #> '{packages,nativeDay}',
      v_payload #> '{packages,nativeOvernight}',
      v_payload #> '{packages,foreignerDay}',
      v_payload #> '{packages,foreignerOvernight}'
    )) as packages(package_item)
    where package_item is not null
      and package_item ->> 'name' = p_package_name
    limit 1;
  end if;

  v_price := nullif(v_package ->> 'price', '')::numeric;
  if v_price is not null then
    v_price := v_price * greatest(1, coalesce(p_participants_count, 1));
  else
    v_price := coalesce(p_price, 0);
  end if;
  v_currency := coalesce(nullif(v_package ->> 'currency', ''), nullif(p_currency, ''), 'ETB');

  return query
  insert into public.registrations (
    user_id, username, full_name, phone, age, participants_count,
    gender, destination, package_name, trip_date, price, currency,
    payment_method, sender_account, transaction_id, payment_status, status
  ) values (
    v_user.id, v_user.username, trim(p_full_name), trim(p_phone),
    p_age, greatest(1, coalesce(p_participants_count, 1)),
    p_gender, p_destination, p_package_name, coalesce(p_trip_date, ''),
    v_price, v_currency,
    coalesce(nullif(p_payment_method, ''), 'Not selected'),
    coalesce(trim(p_sender_account), ''), '',
    v_payment_status, 'pending'
  )
  returning *;
end;
$$;

create or replace function public.get_user_bookings(p_session_token uuid)
returns setof public.registrations
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id bigint;
begin
  v_user_id := public.valid_site_user(p_session_token);
  return query
    select *
    from public.registrations
    where user_id = v_user_id
    order by created_at desc;
end;
$$;

create or replace function public.submit_booking_payment(
  p_session_token uuid,
  p_hike_id text,
  p_sender_account text,
  p_transaction_id text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id bigint;
begin
  v_user_id := public.valid_site_user(p_session_token);
  update public.registrations
  set
    sender_account = coalesce(trim(p_sender_account), ''),
    transaction_id = '',
    payment_status = case
      when nullif(trim(p_sender_account), '') is not null then 'submitted'
      else payment_status
    end
  where user_id = v_user_id
    and hike_id = p_hike_id;

  return found;
end;
$$;

-- Keep browser access simple. Security is enforced by RPC session tokens.
alter table public.site_content disable row level security;
alter table public.site_defaults disable row level security;
alter table public.admins disable row level security;
alter table public.admin_sessions disable row level security;
alter table public.site_users disable row level security;
alter table public.site_user_sessions disable row level security;
alter table public.registrations disable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.site_content to anon, authenticated;
grant select on public.site_defaults to anon, authenticated;
grant execute on function public.admin_login(text, text) to anon, authenticated;
grant execute on function public.admin_current(uuid) to anon, authenticated;
grant execute on function public.admin_logout(uuid) to anon, authenticated;
grant execute on function public.admin_add_admin(uuid, text, text, text) to anon, authenticated;
grant execute on function public.admin_update_profile(uuid, text) to anon, authenticated;
grant execute on function public.admin_change_password(uuid, text, text) to anon, authenticated;
grant execute on function public.admin_get_content(uuid) to anon, authenticated;
grant execute on function public.admin_save_content(uuid, jsonb) to anon, authenticated;
grant execute on function public.admin_get_registrations(uuid) to anon, authenticated;
grant execute on function public.admin_get_site_users(uuid) to anon, authenticated;
grant execute on function public.admin_delete_site_user(uuid, bigint) to anon, authenticated;
grant execute on function public.admin_update_registration(uuid, bigint, text, text) to anon, authenticated;
grant execute on function public.user_signup(text, text, text) to anon, authenticated;
grant execute on function public.user_login(text, text) to anon, authenticated;
grant execute on function public.get_current_user(uuid) to anon, authenticated;
grant execute on function public.user_logout(uuid) to anon, authenticated;
grant execute on function public.create_booking(uuid, text, text, int, int, text, text, text, text, numeric, text, text, text, text) to anon, authenticated;
grant execute on function public.get_user_bookings(uuid) to anon, authenticated;
grant execute on function public.submit_booking_payment(uuid, text, text, text) to anon, authenticated;
